@startuml

|Kunde|
start
: Send ordre;
|It-system|
: Vidresend ordre til salgsmedarbejder via email;
|Salgsmedarbejder|
: Læs ordre;
while (problemer eller manglende information?) is (true)
    : Send email om problemet til kunden;
    |Kunde|
    :Besvar salgsmedarbejder;
    |Salgsmedarbejder|
    : Læs svar givet af kunde;
endwhile (false)
|It-system|
: Beregner stykliste;
|Salgsmedarbejder|
while (Tilbud ikke accepteret) is (true)
: Send tilbud til kunde;
|Kunde|
: Accepter eller afvis tilbud;
endwhile (false)
|Salgsmedarbejder|
: Marker som accepteret;
: Videresend information\n
 til lageransvarlig;
|Lageransvarlig|
: Opdatér forældet stykliste;
: Saml materialer på stykliste;
|Kunde|
: Afhent materialer;
: Byg carport;
end
@enduml