@startuml

title Activitetsdiagram over nuv?rende bestillingsprocess \n

|Kunde|
start
: Send ordre;
|It-system|
: Vidresend ordre til salgsmedarbejder
 via email;
|Salgsmedarbejder|
: L?s ordre;
while (problemer med ordre, eller manglende information?) is (true)
    : Send email om problemet til kunden;
    |Kunde|
    :Besvar sp?rgsm?l givet af salgsmedarbejder;
    |Salgsmedarbejder|
    : L?s svar givet af kunde;
endwhile (false)
|It-system|
: Beregner stykliste;
|Salgsmedarbejder|
while (Betaling ikke godkendt) is (true)
: Send faktura;
|Kunde|
: Betal;
endwhile (false)
|Salgsmedarbejder|
: Giv information vidre til lageransvarlig;
|Lageransvarlig|
: Fix for?ldet stykliste;
: Saml materialer p? stykliste;
|Kunde|
: Afhent materialer;
: Byg carport;