@startuml

title Activitetsdiagram over nuværende bestillingsprocess \n

|Kunde|
start
: Send ordre;
|It-system|
: Vidresend ordre til salgsmedarbejder via email;
|Salgsmedarbejder|
: Læs ordre;
while (problemer eller manglende information?) is (true)
    : Send email om problemet til kunden;
    |Kunde|
    :Besvar salgsmedarbejder;
    |Salgsmedarbejder|
    : Læs svar givet af kunde;
endwhile (false)
|It-system|
: Beregner stykliste;
|Salgsmedarbejder|
repeat
: Send tilbud til kunde;
|Kunde|
if ("acceptér tilbud") then (ja)
|It-system|
: Marker som accepteret;
: Send information til lageransvarlig;
|Lageransvarlig|
: Saml materialer på stykliste;
|Kunde|
: Afhent materialer;
: Byg carport;
else (nej)
endif
end
@enduml