@startuml

|Kunde|
start
: Send ordre;
|It-system|
: Gem ordre;
|Salgsmedarbejder|
: Læs ordre;
while (problemer eller manglende information?) is (true)
    : Send email om problemet til kunden;
    |Kunde|
    :Besvar salgsmedarbejder;
    |Salgsmedarbejder|
    : Læs svar givet af kunde;
endwhile (false)
|It-system|
repeat
|It-system|
: Beregn stykliste;
|Salgsmedarbejder|
while (Tilbud accepteret?) is (false)
|Salgsmedarbejder|
: Beregn stykliste;
: Send tilbud til kunde;
|Kunde|
: Accepter eller afvis tilbud;
endwhile (true)
|It-system|
: Beregn stykliste;
: Videresend information\n
 til lageransvarlig;
|Lageransvarlig|
: Samle materialer på stykliste;
|Kunde|
: Afhent materialer;
: Byg carport;
end
@enduml